### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Harvzor** [tommyku/start-page-bios#1]
Hey, I love this start page!

Could you consider adding a license to it? Preferably something like [MIT](https://opensource.org/licenses/MIT) or [Unlicense](https://unlicense.org/)?

Currently, I'm technically not supposed to copy this repo as it would infringe on your copyright.

I'd like to fork this repository and add it to https://customstart.page/ - a website where I allow users to customise start pages.

The fork of this start page would be kept opensource and would be under this account: https://github.com/custom-start-page

Thanks for reading this.

**Comment by tommyku** [comment]
Yap done #2 
Thank you for the suggestion @Harvzor

**Comment by harvzor** [comment]
@tommyku I've added your start page to my website: https://bios.customstart.page

It can be edited to the users preference: https://bios.customstart.page/preview

The modified source code: https://github.com/custom-start-page/bios

It took a few changes to your original source to get it integrated but I'm very happy with the results. Thanks for creating this awesome start page!
